import Head from "next/head";

import Sidebar from "@components/Sidebar";
import HeaderContent from "@components/HeaderContent";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<>
				<p className=" text-center py-8">Bienvenido al Index Page</p>
			</>
		</div>
	);
}
